### ISSUE TITLE
pml controller breaks when given non txt file

### ISSUE THREAD

**Issue by 22a** [tom-and-the-toothfairies/pathways#50]
When passing any non text file the controller complains about encoding and spits out a 500

```
[info] POST /api/pml
[debug] Processing by Panacea.PmlController.upload/2
  Parameters: %{"_csrf_token" => "RxdHWDk+R0gDUQ4pAHYKPANdbwAIEAAA1M44ngr8FiOaz4kSje8MGw==", "_utf8" => "✓", "file" => %Plug.Upload{content_type: "image/png", filename: "panacea_vial.png", path: "/var/folders/5p/95qqd109569dftcb4yd0dwbc0000gn/T//plug-1487/multipart-698596-812190-3"}}
  Pipelines: [:browser]
[info] Sent 500 in 114ms
[error] #PID<0.315.0> running Panacea.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/pml
** (exit) an exception was raised:
    ** (UnicodeConversionError) invalid encoding starting at <<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 10, 214, 0, 0, 10, 213, 8, 6, 0, 0, 0, 109, 168, 9, 74, 0, 0, 0, 9, 112, 72, 89, 115, 0, 0, 11, 19, 0, 0, 11, 19, 1, ...>>
        (elixir) lib/string.ex:1801: String.to_charlist/1
        (panacea) lib/panacea/pml/parser.ex:9: Panacea.Pml.Parser.parse/1
        (panacea) web/controllers/pml_controller.ex:7: Panacea.PmlController.upload/2
        (panacea) web/controllers/pml_controller.ex:1: Panacea.PmlController.action/2
        (panacea) web/controllers/pml_controller.ex:1: Panacea.PmlController.phoenix_controller_pipeline/2
        (panacea) lib/panacea/endpoint.ex:1: Panacea.Endpoint.instrument/4
        (panacea) lib/phoenix/router.ex:261: Panacea.Router.dispatch/2
        (panacea) web/router.ex:1: Panacea.Router.do_call/2
        (panacea) lib/panacea/endpoint.ex:1: Panacea.Endpoint.phoenix_pipeline/1
        (panacea) lib/plug/debugger.ex:123: Panacea.Endpoint."call (overridable 3)"/2
        (panacea) lib/panacea/endpoint.ex:1: Panacea.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/peter/Desktop/pathways/panacea/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by 22a** [comment]
Fixed in https://github.com/tom-and-the-toothfairies/pathways/pull/29/commits/04dce747bb0d34d38939b32d5a3105cff62c9af1#diff-e43426d72e13b98150797378b92a5577R4 by making the :upload handler only match on valid `Plug.Upload`

**Comment by houli** [comment]
Still happening for me Pete

**Comment by 22a** [comment]
Pardon me, will investigate!

**Comment by houli** [comment]
Think what will need to happen is catch the `UnicodeConversionError` here https://github.com/tom-and-the-toothfairies/pathways/blob/iteration-2/panacea/lib/panacea/pml/parser.ex#L9

**Comment by 22a** [comment]
parser.ex is perfect, the controller should never ask the parser to attempt to parse a garbled string 🥅

**Comment by c-brenn** [comment]
Perhaps `String.valid?` does what we want?
